trigger:
- main

resources:
- repo: self

variables:
  tag: 'v1.0.01'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # Checkout the code
    - checkout: self

    # Login to DockerHub using the service connection
    - task: Docker@2
      displayName: Docker login
      inputs:
        command: login
        containerRegistry: 'docker-azure'  # Replace this with your actual service connection name

    # Build the Docker image
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/gs-spring-boot/Dockerfile'
        tags: |
          bruno74t/spring-boot-java:$(tag)

    # Push the Docker image to DockerHub
    - task: Docker@2
      displayName: Push Docker image
      inputs:
        command: push
        repository: bruno74t/spring-boot-java
        tags: |
          $(tag)
